### ISSUE TITLE
The App version you are using is outdated

### ISSUE THREAD

**Issue by zaporozhetsAnton** [idnow/de.idnow.android.sdk#16]
Hello, I'm using this module https://github.com/bitwala/react-native-idnow
And unfortunately, I get an error "The App version you are using is outdated. Please update the app before trying again."
I looked inside android part of this library and sow that it uses de.idnow.sdk.IDnowSDK
Could anyone help me? Code that throws me an error - https://prnt.sc/s349gr

**Comment by SlawomirLeski** [comment]
Hallo @zaporozhetsAnton ,

looks like you mix Android SDks. Your comment is connected to this Android SDK: https://github.com/idnow/de.idnow.android

So would you like to integrate Videoidentification or Autoidentification SDK?
All the best

**Comment by SlawomirLeski** [comment]
I will close this ticket, if you will need help, please reopen or create new one.

Kind regards,
Slawomir Leski

**Comment by zaporozhetsAnton** [comment]
Hi @SlawomirLeski, thank you for answering. I have created an issue for Android SDK too. Just didn't know where I need to create an issue, here or at sdk repo.
