### ISSUE TITLE
Trying to bridge AutoIdent to React Native

### ISSUE THREAD

**Issue by yberstad** [idnow/de.idnow.android.sdk#40]
Hi!

I'm having a hard time trying to bridge the https://github.com/idnow/de.idnow.android.sdk (AutoIdent) for usage in React Native. 
If I look at the https://github.com/idnow/de.idnow.android (eSign), there are example how to configure the SDK, but I cannot find similar options in the de.idnow.android.sdk (AutoIdent) package?

When I try to follow the example in this SDK, get this non informative error when looking in the logcat log-file:
```
ReactNative: RCTIDNowModule.onIdentResult -> getIDnowStatusCode:ERROR

RCTIDNowModule: Error: It looks like you are trying to perform a VideoIdent, PhotoIdent or E-sign. 
Please try again using our Online Ident App.
```

I have created a sample application to reproduce the error, located here:
https://github.com/yberstad/IDNowBN

1. Clone repo
2. yarn install
3. npx react-native run-android
4. Press 'Start identification', once running on device

I have tried to follow the guide https://github.com/idnow/de.idnow.android.sdk, but I found that I also had to add the following dependencies, from looking at exceptions popping up in logcat log-files:
```
    implementation 'org.slf4j:slf4j-android:1.7.12'
    implementation "com.squareup.okhttp3:okhttp:4.2.2"
    implementation "com.squareup.okhttp3:logging-interceptor:4.2.2"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:4.2.1"
```
If I'm doing something wrong, or if this is due to running it as a RN bridge, or if the doc is missing something I'm not sure? 

I see that some kind of communication starts, when calling `idnowSdk.startIdent(identId, this);` based on this log line:
`OkHttp  : <-- 200 OK https://api.test.idnow.de/api/v1/TST-DJCER (2265ms)
`

The full logcat file is located here:
https://github.com/yberstad/IDNowBN/blob/master/logcat.txt 

I have also had a look at this repo, but they are using de.idnow.android (eSign) instead of the de.idnow.android.sdk (AutoIdent). 
https://github.com/bitwala/react-native-idnow

Any help is much appreciated!

**Comment by SlawomirLeski** [comment]
Hi @yberstad, 

from your ERROR code, looks like you are doing correct, but you just tried token from Videoident. 
Please check your app with this token: `TST-YTWWN`.

https://github.com/idnow/de.idnow.android - this is SDK for VideoIdent + eSigning
https://github.com/idnow/de.idnow.android.sdk - this is SDK for AutoIdent

Hope it will help you, 
kind regards!

**Comment by yberstad** [comment]
@SlawomirLeski, thanks for your quick respons! And now it worked, thank you so much :-)

I have another question after testing the flow, how can I provide the user with some detailed feedback when things go wrong?
 
The reason I'm asking is, if I try to start the process again I get the following generic error:

```
ERROR: The Ident-ID you entered is incorrect. Please check your Ident-ID before trying again.
```

Which is taken from the IDnowResult class, having the following properties:
```
getIDnowStatusCode()
getMessage()
```

But if I look at the logcat log-file again, I see this more detailed error message. 

```
OkHttp  : <-- 412 Precondition Failed 
https://api.test.idnow.de/api/v1/demodatacapture/identifications/TST-YTWWN/start

OkHttp  : {"errors":[{"cause":"PRECONDITION_FAILED","errorType":"IDENTIFICATION_FINISHED",
"id":"49731139","key":null,"message":"The identification was already finished","translationKey":null}]}
```

How can I get hold of this information? 
It would be better to tell the customer that he/she has already completed the process, than telling the customer that Ident-ID is incorrect. 

And in addition, since we have customers in various markets, we also need to provide our users with some localized feedback. This is a bit more tricky, only getting back this kind of generic error code / message.

BR, Øyvind.

**Comment by SlawomirLeski** [comment]
Hi,

from my knowledge, this is intentionally, we do not want to show to user if identification was done successfully (security reasons). But your backed should know about current status because of webhook notification.

If you would like to discuss more about the flow and messages, please contact our customer success team:
https://www.idnow.io/contact/support/

I will close the issue, because it works now.

Have a nice day, all the best!
Slawomir Leski

**Comment by yberstad** [comment]
@SlawomirLeski, thanks for your help, much appreciated!
