### ISSUE TITLE
android.view.InflateException: Binary XML file line #80: Binary XML file line #80: Error inflating class de.idnow.core.ui.component.IDnowPrimaryButton

### ISSUE THREAD

**Issue by worm69** [idnow/de.idnow.android.sdk#52]
Hi with implementation(name: 'idnow-platform', ext: 'aar', version: '4.10.0') i have a error inflating de.idnow.core.ui.component.IDnowPrimaryButton
![imagem](https://user-images.githubusercontent.com/12191069/133238172-9d12ff87-e940-45a2-ba55-e44ab7ed2996.png)
Can help?

**Comment by rfejer-idnow** [comment]
This looks like an SDK integration issue, not specifically a problem with IDnowPrimaryButton. Do you still have this issue?
