### ISSUE TITLE
Broad ProGuard consumer rules

### ISSUE THREAD

**Issue by mrjameshamilton** [idnow/de.idnow.android.sdk#56]
In your ProGuard consumer rules you have rules controlling optimization passes and removal of logging. These kind of rules don't belong in consumer rules because, for example, a user of your library will have logging removed when they do not expect it.  Rules for the removal of logging belong in your project proguard rules file.

```
-ignorewarnings
-optimizationpasses 5
-assumenosideeffects class android.util.Log {
  public static *** v(...);
  public static *** d(...);
  public static *** i(...);
  public static *** w(...);
  public static *** e(...);
}
```

**Comment by sleski** [comment]
Issue is closed. Please reopen if you have any more problems.
Regards!
