### ISSUE TITLE
Design configuration for autoident?

### ISSUE THREAD

**Issue by loki344** [idnow/de.idnow.android.sdk#66]
I'm currently integrating the autoident SDK in our App and I am looking for more configuration possibilities. 

Does this SDK plan to support custom design configurations like the videoident SDK https://github.com/idnow/de.idnow.android#design-configuration ?

Additionally, is there a function/configuration to enable the "error/success view" like in videoident
```
IDnowSDK.setShowVideoOverviewCheck(<true/false>, <Context>);
IDnowSDK.setShowErrorSuccessScreen(<true/false>, <Context>);
```

Thanks for your response

**Comment by mtidnow** [comment]
Hi Loki244, thank you for the raised questions and requests. We are planning to add custom design configuration possibilities in future releases. The idea is to have a common approach for both of the products in the end.
The timeline would be somewhere Q1 23
