### ISSUE TITLE
[Question] How can I do design customizations

### ISSUE THREAD

**Issue by mkutlev** [idnow/de.idnow.android.sdk#72]
I want to do some customizations to the IDnow flow to look similar to the other screens of our app.
Here are the questions I have:
 - What customizations are possible? E.g. theme colors, font, changing images.
 - Is there a sample app showing how to do the customizations?
 - Is there a better place to ask for this?

**Comment by sebastian-schipor-idnow** [comment]
@mkutlev Thanks for reaching out. The customizations in our SDK are done via a customer configuration that we receive at runtime. Based on the generated ident token used to launch the SDK, we are getting the theme configs and apply them.
They include: fonts, colors, animations, images, string translations.

Please get in touch with IDnow customer support if you want specific customizations for your customer configuration.
