### ISSUE TITLE
What are the reasons for IDnowStatusCode.ERROR?

### ISSUE THREAD

**Issue by mkutlev** [idnow/de.idnow.android.sdk#77]
Hi,
I need help with the error handling.

I have a few questions:
 - What are the reasons for IDnowStatusCode.ERROR? 
 - Are there different types of errors?
 - Would retrying to open IDnow Ident flow help?

**Comment by sebastian-schipor-idnow** [comment]
Hello @mkutlev ,

For now, the status `IDnowStatusCode.ERROR ` is an generic error returned by our SDK for all types of errors (API, server exceptions, socket erors). All these cases have a specific message inside `IDnowResult.getMessage()`

We currently have in plan to improve the error handling and also inform the host app if the ident can be retried or not. 

We will keep you posted with the progress!

Regards,
Sebastian
