### ISSUE TITLE
How to change button background

### ISSUE THREAD

**Issue by mkutlev** [idnow/de.idnow.android.sdk#78]
Hi,

I integrated the SDK to my app. The problem is that the styles are very different. In #72 you said that the colors will change automatically but it did not work.

Could you share which theme attributes does the SDK use to be able to make the screens look more consistent to my app?
Here are some of the colors I need to change:
 - Button background color
 - Button text color
 - Text color for TextView-s
 - Highlighted text color (for links)
 - Status bar background

Here are some screens having the components:

Screen with links and text | Screen with button
---|---
<img width="300" src="https://user-images.githubusercontent.com/1737507/191925326-3682262b-0a73-42ba-a784-b14a200e55b5.png"/> | <img width="300" src="https://user-images.githubusercontent.com/1737507/191925461-80dfb58f-9b89-442d-9138-5730059e759e.png"/>

**Comment by sebastian-schipor-idnow** [comment]
hello @mkutlev 
So, the keys for these customizations are as follows:

- Button background color: `public.idnow.platform.customColors.primaryButtonColor`
- Button text color:` public.idnow.platform.customColors.primaryButtonTextColor`
      - pressed color: `public.idnow.platform.customColors.primaryButtonPressedColor`
      - disabled color: `public.idnow.platform.customColors.buttonDisabledColor`
- Text color for TextView-s: `public.idnow.platform.customColors.textColor`
- Highlighted text color (for links): `public.idnow.platform.customColors.primaryColor`
- Status bar background: `public.idnow.platform.customColors.primaryColor`

You need to get in touch with the IDnow support team and ask them to setup your configurations file for your customer shortname. You will need to provide them all your colors, animations, fonts etc. that you want to have in the IDnow SDK for your customer. 

The support team will provide further details on how to configure your theme.

Once this is done, when the SDK is launched, it will get all the theme configurations from remote and apply it.

Regards,
Sebastian
